# Generated by Django 4.1.4 on 2022-12-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/', max_length=1000, verbose_name='Сссылка на ресурс(возможны пространства имен)'),
        ),
    ]
