# Generated by Django 4.1.4 on 2022-12-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='url_is_namespace',
            field=models.BooleanField(default=False, verbose_name='named URL'),
        ),
    ]
